---
- name: Create the .aws directory
  file:
    path: ~/.aws
    state: directory
    mode: '0755'

- name: Stat Credentials File
  stat:
    path: ~/.aws/credentials
  register: aws_creds

- name: Copy Credentials File to Filesystem
  copy:
    src: "{{ role_path }}/aws/files/credentials"
    dest: ~/.aws/credentials
    mode: '0755'
  when: aws_creds.stat.exists == false

- name: Stat Config File
  stat:
    path: ~/.aws/config
  register: aws_config

- name: Copy Config File to Filesystem
  copy:
    src: "{{ role_path }}/aws/files/config"
    dest: ~/.aws/config
    mode: '0755'
  when: aws_config.stat.exists == false

