---
#####
# ZSH Profile
#####
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Apt Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - zsh
    - powerline
    - fonts-powerline

- name: Register Zsh executable location
  command: which zsh
  register: which_zsh

- name: Change the current shell to Zsh
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ which_zsh.stdout }}"

- name: Check Oh My Zsh Installation
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_dir

- name: Installing Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: ohmyzsh_dir.stat.exists == false

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: zshrc_file

- name: Backup the installed .zshrc file
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc.bak
    follow: no
  when: zshrc_file.stat.exists == true

- name: Remove the installed .zshrc file
  file:
    path: ~/.zshrc
    state: absent
  when: zshrc_file.stat.exists == true

- name: Adding Autosuggest plugin to zsh
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Make Autosuggest plugin executable
  file:
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    mode: '0700'

- name: Adding Syntax Highlighting plugin to zsh
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Make Syntax Highlighting plugin executable
  file:
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    mode: '0700'

- name: Linking .zshrc
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: ~/.zshrc
    state: link
    mode: u+rwx,g+rx,o+rx

- name: Linking .zshrc_local template
  template:
    src: "{{ role_path }}/templates/zshrc_local.j2"
    dest: ~/.zshrc_local
    mode: u+rwx

