#cloud-config

package_update: true
package_upgrade: true

packages:
  - ansible
  - git
  - zsh

ssh_pwauth: false

runcmd:
  - |
    #!/bin/bash
    set -eux -o pipefail
    sudo chsh -s "$(which zsh)" "$(whoami)"
    cd "$HOME"
    if [ ! -d dotfiles ]; then
      git clone https://github.com/aljendro/dotfiles-vm.git dotfiles
    fi
