#!/bin/bash

# Simple (uncomplected) install script for all dependencies.
#
# Maintainer: Alejandro Alvarado <alejandro.alvarado0650144@gmail.com>

set -e

__summary="
Bootstraps a VM by installing dependencies and linking dotfiles.

Usage: install
"

echo "This script has yet to be fully tested."
echo "Thes are are 'Notes' on what/how to install deps at the moment."

exit 1

##################################################
########### Package Manager Install ##############
##################################################

sudo dnf -y update
sudo dnf -y upgrade
sudo dnf -y install                \
  bat                              \ # dev
  chromium                         \ # dev
  clojure                          \ # dev
  fd-find                          \ # dev
  git-credential-libsecret         \ # git
  git-delta                        \ # git
  gnome-tweak-tool                 \ # dev
  java-1.8.0-openjdk-devel.aarch64 \ # clojure
  java-11-openjdk-devel.aarch64    \ # clojure
  jq                               \ # dev
  libstdc++-static                 \ # sumneko_lua
  ninja-build                      \ # sumneko_lua
  ripgrep                          \ # dev
  stow                             \ # dotfiles
  tmux                             \ # dev
  tree                             \ # dev
  watchman                         \ # dev
  xclip                            \ # dev
  zsh                                # dev

##################################################
#################### Shell  ######################
##################################################

if [ $SHELL != $(which zsh) ];then
  sudo chsh -s $(which zsh)
  [ ! -d $HOME/.oh-my-zsh ] && sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  [ ! -f $HOME/.zshrc_local ] && touch $HOME/.zshrc_local && echo "export DOTFILES_DIR=$DOTFILES_DIR\n" >> .zshrc_local
  [ ! -f $HOME/.zshrc_vm_local ] && touch $HOME/.zshrc_vm_local
  rm $HOME/.zshrc
fi

##################################################
############### Package Managers #################
##################################################

##################### NVM ########################

if [ ! -f $HOME/.nvm/nvm.sh ]; then
  mkdir -p /tmp/dotfiles/nvm
  cd /tmp/dotfiles/nvm
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
fi
source $HOME/.nvm/nvm.sh

##################### Node #######################

NODE_VERSION_CHECK=$(node --version)

if [ $NODE_VERSION_CHECK != 'v14.17.1' ];then
  nvm install 14.17.1
  nvm alias default 14.17.1
fi

#################### Packer ######################

if [ ! -f $HOME/.local/share/nvim/site/pack/start/packer.vim ];then
  git clone --depth 1 https://github.com/wbthomason/packer.nvim\
   $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

##################################################
################### Packages #####################
##################################################

##################### Rust #######################

if ! command -v rustup &> /dev/null;then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

###################### Go ########################

if ! command -v go &> /dev/null;then
  mkdir /tmp/dotfiles/go
  cd /tmp/dotfiles/go
  if [[ $(uname -m) == 'aarch64' ]]; then
    curl -OL https://go.dev/dl/go1.17.5.linux-arm64.tar.gz
    GO_SHASUM=$(sha256sum go1.17.5.linux-arm64.tar.gz | cut -d' ' -f1)
    if [[ $GO_SHASUM == '6f95ce3da40d9ce1355e48f31f4eb6508382415ca4d7413b1e7a3314e6430e7e' ]];then
      sudo rm -rf /usr/local/go
      sudo tar -C /usr/local -xzf go1.17.5.linux-arm64.tar.gz
    fi
  else
    curl -OL https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
    GO_SHASUM=$(sha256sum go1.17.5.linux-arm64.tar.gz | cut -d' ' -f1)
    if [[ $GO_SHASUM == 'bd78114b0d441b029c8fe0341f4910370925a4d270a6a590668840675b0c653e' ]];then
      sudo rm -rf /usr/local/go
      sudo tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
    fi
  fi
fi

##################### AWS ########################

if [ ! -d $HOME/.aws ];then
  mkdir $HOME/.aws
  [ ! -f $HOME/.aws/config ] && cp $DOTFILES_DIR/files/aws/config $HOME/.aws/
  [ ! -f $HOME/.aws/credentials ] && cp $DOTFILES_DIR/files/aws/credentials $HOME/.aws/
fi

#################### Docker ######################

if ! command -v docker &> /dev/null;then
  sudo dnf -y install dnf-plugins-core
  sudo dnf -y config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
  sudo dnf -y install docker-ce docker-ce-cli containerd.io
  sudo groupadd docker
  sudo usermod -aG docker $USER
fi

################ Docker Compose ##################

if ! command -v docker-compose &> /dev/null;then
  mkdir /tmp/dotfiles/docker-compose
  cd /tmp/dotfiles/docker-compose
  curl https://github.com/docker/compose/releases/download/v2.2.1/docker-compose-linux-aarch64 \
    -o docker-compose
  chmod +x docker-compose
  sudo mv docker-compose /usr/local/bin/
fi

################### Fonts ########################

if [ ! -f $HOME/.local/share/fonts/RobotoMono.ttf ];then
  mkdir /tmp/dotfiles/fonts
  cd /tmp/dotfiles/fonts
  curl https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/RobotoMono/Medium/complete/Roboto%20Mono%20Medium%20Nerd%20Font%20Complete.ttf \
    -o RobotoMono.ttf
  mkdir -p $HOME/.local/share/fonts
  sudo mv RobotoMono.ttf $HOME/.local/share/fonts
  sudo fc-cache -fv
fi

################### NVIM #########################

[ ! -d $HOME/.config/nvim/sessions ] && mkdir -p $HOME/.config/nvim/sessions

if ! command -v nvim &> /dev/null;then
  mkdir /tmp/dotfiles/neovim
  cd /tmp/dotfiles/neovim
  git clone https://github.com/neovim/neovim
  git checkout tags/v0.6.0
  make CMAKE_BUILD_TYPE=RelWithDebInfo
  sudo make install
fi

################### Video ########################

sudo dnf -y install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
sudo dnf -y groupupdate sound-and-video

################### Misc. ########################

npm install -g typescript live-server eslint_d yarn neovim prettier serverless jest aws-cdk csvtojson
pip3 install pynvim==0.4.3 awscli

if ! command -v lua-format &> /dev/null;then
  sudo luarocks install --server=https://luarocks.org/dev luaformatter
fi

if [ ! -d $HOME/.local/share/nvim/lsp_servers/sumneko_lua ] &> /dev/null;then
  # TODO: Revaluate install/build manually
  # Must install/build manually because lsp installer installing amd64 version
  mkdir /tmp/dotfiles/lua
  cd /tmp/dotfiles/lua
  git clone --depth 1 https://github.com/sumneko/lua-language-server.git
  cd lua-language-server
  git submodule update --init --recursive
  cd 3rd/luamake
  ./compile/install.sh
  cd ../..
  ./3rd/luamake/luamake rebuild
  cd /tmp/dotfiles/lua
  mkdir -p $HOME/.local/share/nvim/lsp_servers/sumneko_lua
  cp -r lua-language-server $HOME/.local/share/nvim/lsp_servers/sumneko_lua/lua-language-server
fi

