---
- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - zsh
      - curl
    state: latest
    update_cache: yes

- name: Register Zsh executable location
  command: which zsh
  register: which_zsh

- name: Change the current shell to Zsh
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ which_zsh.stdout }}"

- name: Check Oh My Zsh Installation
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_dir

- name: Installing Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: ohmyzsh_dir.stat.exists == false

- name: Adding Autosuggest plugin to zsh
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Make Autosuggest plugin executable
  file:
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    mode: '0755'

- name: Adding Syntax Highlighting plugin to zsh
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Make Syntax Highlighting plugin executable
  file:
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    mode: '0755'

- name: Generating .zshrc_local
  template:
    src: "{{ role_path }}/templates/zshrc_local.j2"
    dest: ~/.zshrc_local
    mode: '0700'

- name: Stat .zshrc_vm_local file
  stat:
    path: ~/.zshrc_vm_local
  register: vm_local

- name: Copying .zshrc_vm_local
  copy:
    src: "{{ role_path }}/files/zshrc_vm_local"
    dest: ~/.zshrc_vm_local
    mode: '0700'
  when: vm_local.stat.exists == false

