---
- name: Downloading Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: /tmp/neovim
    version: v0.5.1
    depth: 1

- name: Build Neovim
  make:
    chdir: /tmp/neovim
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install Neovim
  become: yes
  make:
    chdir: /tmp/neovim
    target: install

- name: Downloading FZF
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: /tmp/fzf
    depth: 1

- name: Install FZF
  shell: install --bin
  args:
    chdir: /tmp/fzf

- name: Creating session directory
  file:
    path: ~/.config/nvim/sessions
    state: directory
    mode: '0700'

- name: Copying .pluginvimrc
  copy:
    src: "{{ role_path }}/nvim/files/.pluginvimrc"
    dest: ~/.pluginvimrc
    mode: '0755'

# TODO: Figure out how to check for async job completion
# - name: Install Packages
#   shell: nvim -u ~/.pluginvimrc --headless +PackerInstall +"!sleep 20" +qall

# - name: Compile Packages
#   shell: nvim -u ~/.pluginvimrc --headless +PackerCompile +"!sleep 15" +qall

# - name: Install Lsp Servers
#   shell: nvim -u ~/.pluginvimrc --headless +"LspInstall {{ item }}" +"!sleep 15" +qall
#   loop:
#     - bash
#     - clojure
#     - css
#     - dockerfile
#     - html
#     - json
#     - lua
#     - rust
#     - typescript
#     - vim
#     - yaml
