---
- name: Downloading Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: /tmp/neovim
    version: v0.5.1
    depth: 1

- name: Build Neovim
  make:
    chdir: /tmp/neovim
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install Neovim
  become: yes
  make:
    chdir: /tmp/neovim
    target: install

- name: Creating session directory
  file:
    path: ~/.config/nvim/sessions
    state: directory
    mode: '0700'

- name: Copying .pluginvimrc
  copy:
    src: "{{ role_path }}/nvim/files/.pluginvimrc"
    dest: ~/.pluginvimrc
    mode: '0755'

- name: Install Packages
  shell: nvim -u ~/.pluginvimrc +PackerInstall

- name: Compile Packages
  shell: nvim -u ~/.pluginvimrc +PackerCompile

- name: Install Lsp Servers
  shell: nvim +LspInstall {{ item }}
  loop:
    - bash
    - clojure
    - css
    - dockerfile
    - html
    - json
    - lua
    - rust
    - typescript
    - vim
    - yaml
