# Move this file to: `~/.amethyst.yml`
# In order to register changes restart Amethyst.
# If you experience issues pulling in the changes you can also quit Amethyst and run: 
# rm ~/Library/Preferences/com.amethyst.Amethyst.plist
# This removes the current preferences and causes a re-load of this file when amethyst restarts.

################################################################################
## Settings
################################################################################

# true to display the name of the layout when moving to a new space (default true).
enables-layout-hud-on-space-change: false

# Boolean flag for whether or not to add margins betwen windows (default false).
window-margins: true

# Add x px margin between windows
# The size of the margins between windows (in px, default 0).
window-margin-size: 5

# List of bundle identifiers for applications to either be automatically floating or automatically tiled based on floating-is-blacklist (default []).
floating:
  - "com.apple.systempreferences"

# true if windows smaller than a 500px square should be floating by default (default true)
float-small-windows: true

# true if dragging and dropping windows on to each other should swap their positions (default false).
mouse-swaps-windows: true

# true if changing the frame of a window with the mouse should update the layout to accommodate the change (default false). Note that not all layouts will be able to respond to the change.
mouse-resizes-windows: true

# true to automatically move to a space when throwing a window to it (default true).
follow-space-thrown-windows: true

# The integer percentage of the screen dimension to increment and decrement main pane ratios by (default 5).
window-resize-step: 5

# true to maintain layout state across application executions (default true).
restore-layouts-on-launch: true

layouts:
  - tall
  - fullscreen

################################################################################
## Keybindings
################################################################################

mod1:
  - option
  - command

mod2:
  - control
  - option
  - command

# Focus the next window in the list going clockwise.
focus-cw:
  mod: mod1
  key: j

# Swap the position of the currently focused window with the next window in the list going clockwise.
swap-cw:
  mod: mod2
  key: j

# Focus the next window in the list going counter-clockwise.
focus-ccw:
  mod: mod1
  key: k

# Swap the position of the currently focused window with the next window in the list going counter-clockwise.
swap-ccw:
  mod: mod2
  key: k

focus-screen-1:
  mod: mod1
  key: s

throw-screen-1:
  mod: mod2
  key: s

focus-screen-2:
  mod: mod1
  key: d

throw-screen-2:
  mod: mod2
  key: d

focus-screen-3:
  mod: mod1
  key: f

throw-screen-3:
  mod: mod2
  key: f

