---
- name: Installing Apt Packages
  become: yes
  apt:
    name: 
      - curl
    state: present
    update_cache: yes

- name: Downloading Rust Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rust_installer
    mode: '0700'

- name: Install Rust
  shell: ./rust_installer -y
  args:
    chdir: /tmp
