---
- name: Get Kernel Release
  shell: uname -r
  register: kernel_release

- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - autoconf
      - automake
      - bat
      - fd-find
      - firefox
      - jq
      - libssl-dev
      - libtool
      - linux-tools-{{ kernel_release.stdout }}
      - pandoc
      - python-dev
      - python-setuptools
      - ripgrep
      - tree
      - universal-ctags
      - xclip
    state: present
    update_cache: yes

- name: Installing Snap Packages
  become: yes
  snap:
    name: bitwarden
    state: present

- name: Check watchman installation
  shell: which watchman
  register: watchman_stat
  ignore_errors: true

- import_tasks: watchman.yml
  when: watchman_stat.rc != 0
