---
#####
# Install packages
#####
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Apt Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - tree
    - inkscape

- name: Installing Snap Packages
  become: yes
  snap:
    name: "{{ item }}"
    state: present
  loop:
    - bitwarden
    - spotify

