---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Apt Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - tree
    - inkscape
    - xclip
    - ripgrep
    - fd-find
    - libssl-dev
    - autoconf
    - automake
    - libtool
    - python-setuptools
    - python-dev

- name: Installing Snap Packages
  become: yes
  snap:
    name: "{{ item }}"
    state: present
  loop:
    - bitwarden
    - spotify
    - universal-ctags

- name: Downloading watchman
  git:
    repo: 'https://github.com/facebook/watchman.git'
    dest: /tmp/watchman
    version: v4.9.0
    depth: 1

- name: Run autogen.sh for watchman
  shell: ./autogen.sh
  args:
    chdir: /tmp/watchman

- name: Run configure for watchman
  shell: ./configure --enable-lenient
  args:
    chdir: /tmp/watchman

- name: Run make for watchman
  shell: make
  args:
    chdir: /tmp/watchman

- name: Install watchman
  become: yes
  shell: make install
  args:
    chdir: /tmp/watchman

