---
- name: Installing Bitwarden
  become: yes
  snap:
    name: bitwarden
    state: present

- name: Installing VSCode
  become: yes
  snap:
    name: code
    classic: yes
    state: present

# TODO: Break this out into its own role for watchman

# - name: Check watchman installation
#   shell: which watchman
#   register: watchman_stat
#   ignore_errors: true

# - import_tasks: watchman.yml
#   when: watchman_stat.rc != 0
