---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Apt Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - tree
    - inkscape
    - xclip
    - ripgrep
    - fd-find
    - libssl-dev
    - autoconf
    - automake
    - libtool
    - python-setuptools
    - python-dev

- name: Installing Snap Packages
  become: yes
  snap:
    name: "{{ item }}"
    state: present
  loop:
    - bitwarden
    - spotify
    - universal-ctags

- name: Check watchman installation
  shell: which watchman
  register: watchman_stat
  ignore_errors: true

- import_tasks: watchman.yml
  when: watchman_stat.rc != 0
