return {
    "nvim-treesitter/nvim-treesitter",
    -- dependencies = { "nvim-treesitter/playground" },
    config = function()
        require("nvim-treesitter.configs").setup({
            ensure_installed = {
                "bash",
                "c",
                "clojure",
                "cmake",
                "comment",
                "commonlisp",
                "cpp",
                "css",
                "diff",
                "dockerfile",
                "fennel",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "glimmer",
                "go",
                "gomod",
                "gosum",
                "gowork",
                "graphql",
                "html",
                "http",
                "ini",
                "javascript",
                "jq",
                "jsdoc",
                "json",
                "json5",
                "jsonc",
                "latex",
                "lua",
                "luadoc",
                "make",
                "markdown",
                "markdown_inline",
                "norg",
                "pem",
                "pug",
                "python",
                "query",
                "regex",
                "rust",
                "scss",
                "sql",
                "svelte",
                "terraform",
                "todotxt",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "vue",
                "yaml",
                "zig",
            },
            indent = { enable = true, disable = { "yaml" } },
            highlight = { enable = true, additional_vim_regex_highlighting = false },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "<leader>y",
                    node_decremental = "<leader>u",
                    node_incremental = "<leader>i",
                },
            },
            playground = {
                enable = false,
                disable = {},
                updatetime = 25,
                persist_queries = false,
                keybindings = {
                    toggle_query_editor = "o",
                    toggle_hl_groups = "i",
                    toggle_injected_languages = "t",
                    toggle_anonymous_nodes = "a",
                    toggle_language_display = "I",
                    focus_language = "f",
                    unfocus_language = "F",
                    update = "R",
                    goto_node = "<cr>",
                    show_help = "?",
                },
            },
        })
    end,
}
