---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install awscli
  become: yes
  apt:
    name: awscli
    state: present

- name: Create the .aws directory
  file:
    path: ~/.aws
    state: directory
    mode: '0700'

- name: Stat Credentials File
  stat:
    path: ~/.aws/credentials
  register: aws_creds

- name: Copy Credentials File to Filesystem
  copy:
    src: "{{ role_path }}/files/credentials"
    dest: ~/.aws/credentials
    mode: '0700'
  when: aws_creds.stat.exists == false

- name: Stat Config File
  stat:
    path: ~/.aws/config
  register: aws_config

- name: Copy Config File to Filesystem
  copy:
    src: "{{ role_path }}/files/config"
    dest: ~/.aws/config
    mode: '0700'
  when: aws_config.stat.exists == false

