---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install awscli
  become: true
  apt:
    name: awscli
    state: present

- name: Create the .aws directory
  file:
    path: ~/.aws
    state: directory
    mode: '0700'

- name: Copy Credentials File to Filesystem
  copy:
    src: "{{ role_path }}/files/credentials"
    dest: ~/.aws/credentials
    mode: '0700'

- name: Copy Config File to Filesystem
  copy:
    src: "{{ role_path }}/files/config"
    dest: ~/.aws/config
    mode: '0700'
