cpus: 2
memory: '4GiB'
disk: '50GiB'

portForwards:
  - guestIP: '::'
    guestPort: 323
    proto: udp
    ignore: true
  - guestIP: '::'
    guestPort: 5353
    proto: udp
    ignore: true
  - guestIP: '::'
    guestPort: 5355
    proto: any
    ignore: true
  - guestIP: '::'
    guestPort: 6010
    proto: any
    ignore: true

ssh:
  forwardX11: true

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      dnf up -y
      dnf install -y ansible git zsh
      chsh -s /bin/zsh "$USER"
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      cd "$HOME"
      if [ ! -d dotfiles ]; then
        git clone https://github.com/aljendro/dotfiles-vm.git dotfiles
      fi
