cpus: 4
memory: '8GiB'
disk: '100GiB'

mounts:
  - location: '~/vm_shared'
    mountPoint: '{{.Home}}/Shared'
    writable: true

portForwards:
  - guestPortRange: [8000, 9000]
    hostPortRange: [8000, 9000]
