---
- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - curl
    state: present
    update_cache: yes

- name: Downloading Go tar file
  get_url:
    url: https://dl.google.com/go/go1.16.5.linux-amd64.tar.gz
    dest: /tmp/go_installer
    mode: '0700'
    checksum: sha256:b12c23023b68de22f74c0524f10b753e7b08b1504cb7e417eccebdd3fae49061

- name: Install Go
  become: yes
  unarchive:
    src: /tmp/go_installer
    dest: /usr/local/
    mode: '0700'
