---
- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - curl
    state: present
    update_cache: yes

- name: Downloading Go tar file
  get_url:
    url: https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz
    dest: /tmp/go_installer
    mode: '0700'
    checksum: sha256:f242a9db6a0ad1846de7b6d94d507915d14062660616a61ef7c808a76e4f1676

- name: Install Go
  become: yes
  unarchive:
    src: /tmp/go_installer
    dest: /usr/local/
    mode: '0755'

- name: Install EFM LSP Server
  shell: go install github.com/mattn/efm-langserver@latest

