---
# TODO: Use Stow to link file

# - name: Linking tmux config
#   file:
#     src: "{{ role_path }}/files/tmux.conf"
#     dest: ~/.tmux.conf
#     state: link
#     mode: u+rwx,g+rx,o+rx

# - name: Adding Themes for tmux
#   git:
#     repo: https://github.com/jimeh/tmux-themepack.git
#     dest: ~/.tmux-themepack

# - name: Make Themes readable
#   file:
#     dest: ~/.tmux-themepack
#     mode: '0700'
