---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Curl Package
  become: yes
  apt:
    name: curl
    state: present

# Sums - https://download-installer.cdn.mozilla.net/pub/devedition/releases/<version>/SHA256SUMS
- name: Downloading Firefox Developer Edition
  get_url:
    url: https://download-installer.cdn.mozilla.net/pub/devedition/releases/79.0b2/linux-x86_64/en-US/firefox-79.0b2.tar.bz2
    dest: "{{ firefox_location }}"
    checksum: sha256:317964a88f1c085f2a261ca4aef00574abfcfe66d67fb6d4cbe96c2e43a36ac0

- name: Extracting Firefox Developer Edition
  become: yes
  unarchive:
    src: "{{ firefox_location }}"
    dest: /opt

- name: Adding Firefox Developer Edition to List
  file:
    src: "{{ role_path }}/files/firefox_dev.desktop"
    dest: ~/.local/share/applications/firefox_dev.desktop
    state: link
    mode: +x

- name: Uninstalling vanilla Firefox
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - firefox

