---
- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install pip packages
  pip:
    name:
      - pynvim==0.4.3
      - cfn-lint
      - jedi
