---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Apt Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - rlwrap
    - openjdk-11-jre
    - leiningen

- name: Downloading Clojure Cli Installer
  get_url:
    url: https://download.clojure.org/install/linux-install-1.10.1.561.sh
    dest: /tmp/clojure_installer
    mode: '0700'

- name: Install Clojure Cli
  become: yes
  command: ./clojure_installer
  args:
    chdir: /tmp

