---
#####
# Install dependencies
#####
- name: Downloading Docker Public Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: "{{ docker_pubkey_location }}"

- name: Loading Docker Public Key into Apt
  become: true
  command: apt-key add {{ docker_pubkey_location }}

- name: Adding Docker to List
  become: true
  shell: echo 'deb [arch=amd64] http://download.docker.com/linux/ubuntu bionic stable' | sudo tee /etc/apt/sources.list.d/docker.list

- name: Downloading Google Public Key
  get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: "{{ google_pubkey_location }}"

- name: Loading Google Public Key into Apt
  become: true
  command: apt-key add {{ google_pubkey_location }}

- name: Adding Google Chrome Stable to List
  become: true
  shell: echo 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list

- name: Downloading Firefox Developer Edition
  get_url:
    url: https://download-installer.cdn.mozilla.net/pub/devedition/releases/77.0b9/linux-x86_64/en-US/firefox-77.0b9.tar.bz2
    dest: "{{ firefox_location }}"
    checksum: sha256:53bdc1301bf0a4c9c8204d5893bf951afd3c5a8ec0870c356fc6e789e934c1b3

- name: Extracting Firefox Developer Edition
  become: true
  unarchive:
    src: "{{ firefox_location }}"
    dest: /opt


- name: Adding Firefox Developer Edition to List
  file:
    src: "{{ dotfiles_dir }}/firefox/firefox_dev.desktop"
    dest: ~/.local/share/applications/firefox_dev.desktop
    state: link
    mode: +x

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Apt Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - tree
    - curl
    - vim
    - inkscape
    - google-chrome-stable
    - zsh
    - powerline
    - fonts-powerline
    - apt-transport-https
    - ca-certificates
    - docker-ce

- name: Installing Snap Packages
  become: yes
  snap:
    name: "{{ item }}"
    state: present
  loop:
    - bitwarden
    - spotify

- name: Uninstalling Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - firefox

- name: Add user to the docker group
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    group: docker

- name: Get Machine Hardware Name
  shell: uname -m
  register: hardware_name

- name: Get Kernel Name
  shell: uname -s
  register: kernel_name

- name: Install Docker Compose
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-{{ kernel_name.stdout }}-{{ hardware_name.stdout }}"
    dest: /usr/local/bin/docker-compose
    mode: +x

