---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Curl Package
  become: yes
  apt:
    name: curl
    state: present

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install latest LTS Nodejs version
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash

- name: Use LTS Nodejs version
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default node
  args:
    executable: /bin/bash

- name: Install fixed Nodejs version for stable use
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 12.18.0
  args:
    executable: /bin/bash

- name: Use 12.18.0 Nodejs version
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias stable-default 12.18.0
  args:
    executable: /bin/bash

- name: Install neovim provider
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use stable-default && npm install -g neovim
  args:
    executable: /bin/bash

