---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Curl Package
  become: yes
  apt:
    name: curl
    state: present

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Nodejs version
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 12.13.0
  args:
    executable: /bin/bash

- name: Use Nodejs version
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default 12.13.0
  args:
    executable: /bin/bash

- name: Install neovim provider
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use default && npm install -g neovim
  args:
    executable: /bin/bash

- name: Install prettier
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use default && npm install -g prettier
  args:
    executable: /bin/bash
