---
- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - make
      - libsecret-1-0
      - libsecret-1-dev
    state: present
    update_cache: yes

- name: Linking .gitconfig
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: ~/.gitconfig
    state: link
    mode: '0700'

- name: Linking .gitignore_global
  file:
    src: "{{ role_path }}/files/gitignore_global"
    dest: ~/.gitignore_global
    state: link
    mode: '0700'

- name: Install Libsecret
  become: yes
  shell: make
  args:
    chdir: /usr/share/doc/git/contrib/credential/libsecret
