---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Linking .gitconfig
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: ~/.gitconfig
    state: link
    mode: '0700'
