---
# TODO: Use stow to link this package

# - name: Linking .gitconfig
#   file:
#     src: "{{ role_path }}/files/gitconfig"
#     dest: ~/.gitconfig
#     state: link
#     mode: '0700'

# - name: Linking .gitignore_global
#   file:
#     src: "{{ role_path }}/files/gitignore_global"
#     dest: ~/.gitignore_global
#     state: link
#     mode: '0700'

# TODO: Move all package installs to single file 

# - name: Install Libsecret
#   become: yes
#   shell: make
#   args:
#     chdir: /usr/share/doc/git/contrib/credential/libsecret
