---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing Vim and Curl
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - vim
    - vim-gtk3

- name: Install Vim-Plug package manager
  command:
    cmd: curl -fLo ~/.vim/autoload/plug.vim --create-dirs
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    creates: ~/.vim/autoload/plug.vim

- name: Linking .vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: ~/.vimrc
    state: link
    mode: u+rwx,g+rx,o+rx

- name: Linking coc-settings.json
  file:
    src: "{{ role_path }}/files/coc-settings.json"
    dest: ~/.vim/coc-settings.json
    state: link
    mode: u+rwx,g+rx,o+rx

- name: Install plugins
  command: vim +PlugInstall +qall

