---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing and Curl
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - python3-neovim

- name: Download latest Neovim
  become: yes
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
    dest: /usr/bin/nvim
    mode: u+rx,g+rx,o+rx

- name: Install Vim-Plug package manager
  command:
    cmd: sh -c 'curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    creates: ~/.local/share/nvim/site/autoload/plug.vim

- name: Linking .vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: ~/.vimrc
    state: link
    mode: u+rwx,g+rx,o+rx

- name: Creating neovim directories
  file:
    path: ~/.config/nvim
    state: directory
    mode: '0700'

- name: Linking init.vim for neovim
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: ~/.config/nvim/init.vim
    state: link
    mode: u+rwx,g+rx,o+rx

# - name: Install plugins
  # command: vim +PlugInstall +qall

- name: Installing Node.js provider
  shell: "{{ role_path }}/files/install-lsp.sh"
  args:
    executable: /bin/bash


