---
- name: Development Machine Setup
  hosts: local
  tasks:
    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]

    - import_role:
        name: dependencies
      tags:
        - dependencies

    - import_role:
        name: zsh
      tags:
        - zsh

    - import_role:
        name: vim
      tags:
        - vim

