---
- name: Development Machine Setup
  hosts: local
  vars:
    google_pubkey_location: /tmp/google_pubkey.pub
    firefox_location: /tmp/firefox_developer_edition.tar.bz2
  tasks:
    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]

    - import_role:
        name: dependencies
      tags:
        - dependencies

    - import_role:
        name: zsh
      tags:
        - zsh

    - import_role:
        name: vim
      tags:
        - vim

