---
- name: Development Machine Setup
  hosts: local
  tasks:
    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]

    - import_role:
        name: packages
      tags:
        - packages

    - import_role:
        name: vim
      tags:
        - vim

    - import_role:
        name: chrome
      tags:
        - chrome

    - import_role:
        name: firefox
      tags:
        - firefox

    - import_role:
        name: zsh
      tags:
        - zsh

    - import_role:
        name: docker
      tags:
        - docker

    - import_role:
        name: javascript
      tags:
        - js
        - web

    - import_role:
        name: aws
      tags:
        - aws
        - web
