---
- name: Development Machine Setup
  hosts: local
  tasks:
    - import_role:
        name: shell
      tags:
        - shell

    - import_role:
        name: package_managers
      tags:
        - package_managers

    - import_role:
        name: packages
      tags:
        - packages

