---
- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Adding Google Cloud SDK to List
  become: yes
  shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list

- name: Downloading Google Cloud Public Key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: "{{ gcp_pubkey_location }}"

- name: Loading Google Cloud Public Key into Apt
  become: yes
  command: apt-key --keyring /usr/share/keyrings/cloud.google.gpg add {{ gcp_pubkey_location }}


- name: Installing Google SDK
  become: yes
  apt:
    name: google-cloud-sdk
    state: present
    update_cache: yes

