vim.cmd("inoreabbrev _f feat:")
vim.cmd("inoreabbrev _x fix:")
vim.cmd("inoreabbrev _b build:")
vim.cmd("inoreabbrev _c chore:")
vim.cmd("inoreabbrev _d docs:")
vim.cmd("inoreabbrev _s style:")
vim.cmd("inoreabbrev _r refactor:")
vim.cmd("inoreabbrev _p perf:")
vim.cmd("inoreabbrev _t test:")
vim.cmd("inoreabbrev _bc BREAKING CHANGE:")

