---
- name: Installing Apt Packages
  become: yes
  apt:
    name:
      - autoconf
      - automake
      - libtool
      - clangd
      - clang
      - libclang-dev
      - bear
    state: present
    update_cache: yes

- name: Installing cmake
  become: yes
  command: snap install cmake --classic
