---
- name: Downloading Google Public Key
  get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /tmp/google_pubkey.pub

- name: Loading Google Public Key into Apt
  become: yes
  command: apt-key add /tmp/google_pubkey.pub

- name: Adding Google Chrome Stable to List
  become: yes
  shell: echo 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list

- name: Installing Chrome
  become: yes
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes

