---
- name: Get Kernel Release
  shell: uname -r
  register: kernel_release

- name: Installing Apt Packages
  become: yes
  apt:
    name:
      # - ripgrep
      - apt-transport-https
      - autoconf
      - automake
      - bat
      - bear
      - build-essential
      - ca-certificates
      - clang
      - clangd
      - curl
      - fd-find
      - firefox
      - fonts-powerline
      - gnome-tweak-tool
      - gnupg
      - jq
      - leiningen
      - libclang-dev
      - libreadline-dev
      - libsecret-1-0
      - libsecret-1-dev
      - libssl-dev
      - libtool
      - linux-tools-{{ kernel_release.stdout }}
      - make
      - openjdk-11-jdk
      - openjdk-8-jdk
      - powerline
      - python-dev
      - python-setuptools
      - python3
      - python3-pip
      - rlwrap
      - software-properties-common
      - tmux
      - tree
      - universal-ctags
      - xclip
      - zsh
    state: latest
    update_cache: yes
